### ISSUE TITLE
ur bone mask is wrong

### ISSUE THREAD

**Issue by lagcompensation** [bloesway/csgo_sdk#1]
old:
` used_by_anything = ( 1 << 19 ) - used_by_hitbox,
  used_mask = ( 1 << 19 ) - used_by_hitbox
`
new:
` used_by_anything = ( 1 << 20 ) - used_by_hitbox,
  used_mask = ( 1 << 20 ) - used_by_hitbox
`

**Comment by bloesway** [comment]
any references?

**Comment by bloesway** [comment]
i decided to have a look at what you said, in the end i was really wrong, sorry. ( in client.dll sig -  E8 ? ? ? ? 5E 5D C2 10 )
![изображение](https://github.com/bloesway/csgo_sdk/assets/142020073/b21d998f-55fb-4125-9cb8-b19635cef502)
