### ISSUE TITLE
issue w/ c_anim_sync::update

### ISSUE THREAD

**Issue by lagcompensation** [bloesway/csgo_sdk#2]
hello again!
https://github.com/bloesway/csgo_sdk/blob/master/csgo/hacks/anim_system/impl/anim_system.cpp#L290-L291
u dont need to interpolate the origin since the game does it for us.
reference:
https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/game/server/player_lagcompensation.cpp#L430

**Comment by bloesway** [comment]
the server uses all the data from LagCompensation only at the moment of firing, doesnt it? also, this is not a client side part, we should do the same as the server does

**Comment by bloesway** [comment]
do you think so? i think it has nothing to do with it, our task is to simulate every choked tick of a player on the client, how can our client know what position the player was, for example, in at 8 choked tick, when we simulate this tick?

**Comment by bloesway** [comment]
if you want to talk in more detail about some problems in cheat, or advise some ideas for implementation, you can write me in discord - bloesway

**Comment by lagcompensation** [comment]
> do you think so? i think it has nothing to do with it, our task is to simulate every choked tick of a player on the client, how can our client know what position the player was, for example, in at 8 choked tick, when we simulate this tick?

this has nothing to do w/ origin interpolation
I will say even so, this interpolation does absolutely nothing since server lag compensation already does it FOR US( about client too same )
